apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-odds
  labels:
    app: worker-odds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-odds
  template:
    metadata:
      labels:
        app: worker-odds
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "worker-odds"
        dapr.io/app-port: "8082"
    spec:
      containers:
      - name: worker-odds
        image: worker-odds:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: APP_PORT
          value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-odds
spec:
  selector:
    app: worker-odds
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
